# --------- gen character parts ---------
mask_created_dir: "gen_characters/mask_created" # Directory for created masks
mask_created_save_dir: "gen_characters/mask_created/testB" # Save directory for created masks - testB
generated_chars_dir: "gen_characters/generated_chars" # CycleGan result directory

checkpoints_dir: "resources/checkpoints"
exp_names: ["font_generation_set2_k4_cluster1", "font_generation_set2_k4_cluster2", "font_generation_set2_k4_cluster3", "font_generation_set2_k4_cluster4"]
fonts_dir: "resources/font_families" # Path to font family file
candidate_mask_sizes: [256, 272, 288, 304, 320, 336, 352, 368, 384] # candidate font size - mask_size_list
right_padding_range: [-20,40] # candidate right paddig size
bottom_padding_range: [0,60] # candidate bottom padding size


# --------- gen text box parts ---------
generated_chars_image_dir: "gen_characters/generated_chars/results/test_latest/images" # rename from exp_name to results at gen_charater.py
fake_image_dir: "gen_characters/fake_images" # Directory for fake images - masked output
mask_image_dir: "gen_characters/mask_images" # Directory for mask images - binary mask
